/*
 * This is one of the biggest three files of source code written and commented by Gage Morgan.
 *
 * Also, this file generates the whole logo by piecing together individual pieces generated by the previous 
 * files.
 *
 * This is the final revision by Gage Morgan, started on October 3rd, 2015, finished on
 * October 17, 2015. In this revision, this compilation serves as commented Cairo for examples 
 * on how to build with the Cairo library.
 */

#include "/usr/include/cairo/cairo.h"

int
main (int argc, char *argv[])
{
        cairo_surface_t *surface = //Sets the Cairo surface context
            cairo_image_surface_create (CAIRO_FORMAT_ARGB32, 421, 615); //Creates Cairo image surface, sets image resolution.
        cairo_t *cr = //Declare *cr as a Cairo context.
            cairo_create (surface); //Sets the Cairo context as a pointer, *cr.

	/* Declaration of first triangle pointer */
	cairo_surface_t *one; 

	/* Declaration of second triangle pointer */
	cairo_surface_t *two; 

	/* Declaration of third triangle pointer */
	cairo_surface_t *three; 

	/* Declaration of fourth triangle pointer */
	cairo_surface_t *four; 

	/* Declaration of fifth triangle pointer */
	cairo_surface_t *five; 

	/* Declaration of sixth triangle pointer */
	cairo_surface_t *six; 

	/* Declaration of seventh triangle pointer */
	cairo_surface_t *seven;	

	/* Declaration of text triangle pointer */
	cairo_surface_t *text; 

	/* Assigns the image of first triangle to the declared pointer */
	cairo_push_group (cr); //Push the image to a surface
	one = cairo_image_surface_create_from_png ("../images/triangle1-color.png"); //Assign generated image to the pointer declared above
	cairo_pop_group_to_source (cr); //Pop it to the image you see

	/* Assigns the image of second triangle to the declared pointer */
	cairo_push_group (cr); //Push the image to a surface
	two = cairo_image_surface_create_from_png ("../images/triangle2-color.png"); //Assign generated image to the pointer declared above
	cairo_pop_group_to_source (cr); //Pop it to the image you see

	/* Assigns the image of third triangle to the declared pointer */
	cairo_push_group (cr); //Push the image to a surface
	three = cairo_image_surface_create_from_png ("../images/triangle3-color.png"); //Assign generated image to the pointer declared above
	cairo_pop_group_to_source (cr); //Pop it to the image you see

	/* Assigns the image of fourth triangle to the declared pointer */
	cairo_push_group (cr); //Push the image to a surface
	four = cairo_image_surface_create_from_png ("../images/triangle4-color.png"); //Assign generated image to the pointer declared above
	cairo_pop_group_to_source (cr); //Pop it to the image you see

	/* Assigns the image of fifth triangle to the declared pointer */
	cairo_push_group (cr); //Push the image to a surface
	five = cairo_image_surface_create_from_png ("../images/triangle5-color.png"); //Assign generated image to the pointer declared above
	cairo_pop_group_to_source (cr); //Pop it to the image you see

	/* Assigns the image of sixth triangle to the declared pointer */
	cairo_push_group (cr); //Push the image to a surface
	six = cairo_image_surface_create_from_png ("../images/triangle6-color.png"); //Assign generated image to the pointer declared above
	cairo_pop_group_to_source (cr); //Pop it to the image you see

	/* Assigns the image of seventh triangle to the declared pointer */
	cairo_push_group (cr); //Push the image to a surface
	seven = cairo_image_surface_create_from_png ("../images/triangle7-color.png"); //Assign generated image to the pointer declared above
	cairo_pop_group_to_source (cr); //Pop it to the image you see

	/* Assigns the image of the generated logo's text to the declared pointer */
	cairo_push_group (cr); //Push the image to a surface
	text = cairo_image_surface_create_from_png ("../images/text.png"); //Assign generated image to the pointer declared above
	cairo_pop_group_to_source (cr); //Pop it to the image you see

	/* Assign pointer to source */
	cairo_set_source_surface (cr, one, 0, 0); //Makes sure the pointers appear all together and make the image using their assigned file
	cairo_paint (cr); //Transfers these images to the final output that you see, it paints the image that you see when compiled/outpuuted

	/* Assign pointer to source */
	cairo_set_source_surface (cr, two, 0, 0); //Makes sure the pointers appear all together and make the image using their assigned file
	cairo_paint (cr); //Transfers these images to the final output that you see, it paints the image that you see when compiled/outpuuted

	/* Assign pointer to source */
	cairo_set_source_surface (cr, three, 0, 0); //Makes sure the pointers appear all together and make the image using their assigned file
	cairo_paint (cr); //Transfers these images to the final output that you see, it paints the image that you see when compiled/outpuuted

	/* Assign pointer to source */
	cairo_set_source_surface (cr, four, 0, 0); //Makes sure the pointers appear all together and make the image using their assigned file
	cairo_paint (cr); //Transfers these images to the final output that you see, it paints the image that you see when compiled/outpuuted

	/* Assign pointer to source */
	cairo_set_source_surface (cr, five, 0, 0); //Makes sure the pointers appear all together and make the image using their assigned file
	cairo_paint (cr); //Transfers these images to the final output that you see, it paints the image that you see when compiled/outpuuted

	/* Assign pointer to source */
	cairo_set_source_surface (cr, six, 0, 0); //Makes sure the pointers appear all together and make the image using their assigned file
	cairo_paint (cr); //Transfers these images to the final output that you see, it paints the image that you see when compiled/outpuuted

	/* Assign pointer to source */
	cairo_set_source_surface (cr, seven, 0, 0); //Makes sure the pointers appear all together and make the image using their assigned file
	cairo_paint (cr); //Transfers these images to the final output that you see, it paints the image that you see when compiled/outpuuted

	/* Assign pointer to source */
	cairo_set_source_surface (cr, text, 0, 0); //Makes sure the pointers appear all together and make the image using their assigned file
	cairo_paint (cr); //Transfers these images to the final output that you see, it paints the image that you see when compiled/outpuuted

	/* Destroy the first triangle surface to free up memory and/or lag */
	cairo_surface_destroy (one); 

	/* Destroy the second triangle surface to free up memory and/or lag */
	cairo_surface_destroy (two); 

	/* Destroy the third triangle surface to free up memory and/or lag */
	cairo_surface_destroy (three);

	/* Destroy the fourth triangle surface to free up memory and/or lag */
	cairo_surface_destroy (four); 

	/* Destroy the first triangle surface to free up memory and/or lag */
	cairo_surface_destroy (five); 

	/* Destroy the first triangle surface to free up memory and/or lag */
	cairo_surface_destroy (six); 

	/* Destroy the first triangle surface to free up memory and/or lag */
	cairo_surface_destroy (seven); 

	/* Destroy the first triangle surface to free up memory and/or lag */
	cairo_surface_destroy (text); 

	/* Write output and clean up */
        cairo_surface_write_to_png (surface, "../images/crstfn-color-text.png"); //Name the resulting image as crstfn-color-text.png
        cairo_destroy (cr); //Destroy the context pointer, frees up memory and/or lag
        cairo_surface_destroy (surface); //Destroy the surface pointer, frees up memory and/or lag

        return 0; //No numbers needed!!
}



